# Generated by Django 2.1.7 on 2019-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProject', '0003_auto_20190524_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/test.jpg', upload_to='img/%y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
