# Generated by Django 2.1.7 on 2019-05-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProject', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/test.jpg', upload_to='img/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
